version: '2'

networks:
  testnetwork:
    driver: bridge
  traefik:
    external:
      name: traefik

services:
  example:
    image: pabardina/gohostname
    networks:
      - testnetwork
      - traefik
    labels:
      - "traefik.frontend.rule=Host:test.bardina.net"
      - "traefik.port=8000"
      - "traefik.backend=example"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.docker.network=traefik"
